version: "3.7"
services:
  # nginx:
  #   build:
  #     context: ./nginx_service
  #   hostname: "nginx"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   environment:
  #     - DOMAIN=${DOMAIN}
  #   networks:
  #     - inventory-network
  #   links:
  #     - back_service
  #   restart: unless-stopped

  mongo:
    hostname: "mongo"
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - data-volume:/data/db
    networks:
      - inventory-network
    restart: unless-stopped

  back_service:
    build:
      context: ./back
    hostname: "back"
    ports:
      - "127.0.0.1:4000:4000"
    links:
      - mongo     
    depends_on:
      - mongo     
    volumes:
      - data-volume:/public/upload
    networks:
      - inventory-network
    restart: unless-stopped

  front_end:
    build:
      context: ./inventory-react-ui
    hostname: "front_end"
    ports:
      - "127.0.0.1:80:3000"
    links:
      - back_service     
    depends_on:
      - back_service     
    networks:
      - inventory-network
    restart: unless-stopped    
        
volumes:
  data-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PWD}/data

networks:
  inventory-network:
    driver: bridge
